// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: expense/proto/expense.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PayerId       uint64                 `protobuf:"varint,2,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExpenseRequest) Reset() {
	*x = AddExpenseRequest{}
	mi := &file_expense_proto_expense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExpenseRequest) ProtoMessage() {}

func (x *AddExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_expense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExpenseRequest.ProtoReflect.Descriptor instead.
func (*AddExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_expense_proto_rawDescGZIP(), []int{0}
}

func (x *AddExpenseRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AddExpenseRequest) GetPayerId() uint64 {
	if x != nil {
		return x.PayerId
	}
	return 0
}

func (x *AddExpenseRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpenseResponse) Reset() {
	*x = ExpenseResponse{}
	mi := &file_expense_proto_expense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseResponse) ProtoMessage() {}

func (x *ExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_expense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseResponse.ProtoReflect.Descriptor instead.
func (*ExpenseResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_expense_proto_rawDescGZIP(), []int{1}
}

func (x *ExpenseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_expense_proto_expense_proto protoreflect.FileDescriptor

const file_expense_proto_expense_proto_rawDesc = "" +
	"\n" +
	"\x1bexpense/proto/expense.proto\x12\aexpense\"a\n" +
	"\x11AddExpenseRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x19\n" +
	"\bpayer_id\x18\x02 \x01(\x04R\apayerId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"+\n" +
	"\x0fExpenseResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2T\n" +
	"\x0eExpenseService\x12B\n" +
	"\n" +
	"AddExpense\x12\x1a.expense.AddExpenseRequest\x1a\x18.expense.ExpenseResponseB\x18Z\x16services/expense/protob\x06proto3"

var (
	file_expense_proto_expense_proto_rawDescOnce sync.Once
	file_expense_proto_expense_proto_rawDescData []byte
)

func file_expense_proto_expense_proto_rawDescGZIP() []byte {
	file_expense_proto_expense_proto_rawDescOnce.Do(func() {
		file_expense_proto_expense_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expense_proto_expense_proto_rawDesc), len(file_expense_proto_expense_proto_rawDesc)))
	})
	return file_expense_proto_expense_proto_rawDescData
}

var file_expense_proto_expense_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_expense_proto_expense_proto_goTypes = []any{
	(*AddExpenseRequest)(nil), // 0: expense.AddExpenseRequest
	(*ExpenseResponse)(nil),   // 1: expense.ExpenseResponse
}
var file_expense_proto_expense_proto_depIdxs = []int32{
	0, // 0: expense.ExpenseService.AddExpense:input_type -> expense.AddExpenseRequest
	1, // 1: expense.ExpenseService.AddExpense:output_type -> expense.ExpenseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_expense_proto_expense_proto_init() }
func file_expense_proto_expense_proto_init() {
	if File_expense_proto_expense_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expense_proto_expense_proto_rawDesc), len(file_expense_proto_expense_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expense_proto_expense_proto_goTypes,
		DependencyIndexes: file_expense_proto_expense_proto_depIdxs,
		MessageInfos:      file_expense_proto_expense_proto_msgTypes,
	}.Build()
	File_expense_proto_expense_proto = out.File
	file_expense_proto_expense_proto_goTypes = nil
	file_expense_proto_expense_proto_depIdxs = nil
}
